import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "./globals.css";

const mulish = Mulish({
  subsets: ["latin-ext"],
});

export const metadata: Metadata = {
  title: "aMORA simulador",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", // Aqui já indica o favicon
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={`${mulish.className} dark antialiased`}>{children}</body>
    </html>
  );
}
